### ISSUE TITLE
EBREAK

### ISSUE THREAD

**Issue by mndstrmr** [microsoft/cheriot-ibex#33]
The Sail requires that on an EBREAK instruction MTVAL is set to the PC. This is not done at the moment.

Update the EBREAK handling code in the controller to the following fixes the issue:
```sv
ebrk_insn_prio: begin
  if (debug_mode_q | ebreak_into_debug) begin
    /* snip */
  end else begin
    /* snip */
    exc_cause_o      = EXC_CAUSE_BREAKPOINT;
    csr_mtval_o      = pc_id_i;
  end
end
```

**Comment by kliuMsft** [comment]
Interesting. This is inherited from the original ibex design I think. Although, per RISC-v privileged spec, I think hardware platform is allowed to set mtval as 0 in this case? Or this is another case where sail wants to use the same setting across all exceptions?

**Comment by mndstrmr** [comment]
If that is the case the Sail does not reflect that.

1. `execute EBREAK` calls
2. `handle_mem_exception(PC, E_Breakpoint())` calls
3. `exception_handler(..., CTL_TRAP(t), PC)` calls
4. `trap_handler(...)`
5. Which sets `mtval = PC`

**Comment by marnovandermaas** [comment]
I don't see `mtval` being mentioned in the spec. In case the spec does not mind I would prefer changing the Sail rather than Ibex.

![image](https://github.com/microsoft/cheriot-ibex/assets/34654485/cafadca0-8282-4e49-9c92-6d3fd5582398)

**Comment by rmn30** [comment]
In that case this seems like an issue with upstream [sail-riscv](https://github.com/riscv/sail-riscv). This looks interesting: https://github.com/riscv/sail-riscv/issues/70

**Comment by marnovandermaas** [comment]
> In that case this seems like an issue with upstream [sail-riscv](https://github.com/riscv/sail-riscv). This looks interesting: [riscv/sail-riscv#70](https://github.com/riscv/sail-riscv/issues/70)

Looks like that is in a newer version of the spec. It's probably better to stay with a ratified version for now though right?

**Comment by kliuMsft** [comment]
Actually I am making a cheriot-specific (only when cheri_pmode = 1) change for this to match sail (which is also required for simulation-based verification).

**Comment by mndstrmr** [comment]
This proves as well, thanks.
