### ISSUE TITLE
Verilator compile fails when compiling with the RV32E parameter set

### ISSUE THREAD

**Issue by ColinSCISemi** [microsoft/cheriot-ibex#39]
## Observed Behavior
As the attached log file shows, [fusesoc.log](https://github.com/user-attachments/files/16245198/fusesoc.log), Verilator compile of the Cheri Ibex fails if the RV32E parameter is set.

## Expected Behavior
RV32E enables 16x GP registers, which matches the CHERIoT spec. Without the RV32E option there are 16x redundant GP registers implemented.

The attached patch, [ibex_cheri_rv32e.patch.txt](https://github.com/user-attachments/files/16245349/ibex_cheri_rv32e.patch.txt), fixes the compile issue for me and has been lightly tested. The patch also propagates the RV32E parameter through the top_tracing module.

## Steps to reproduce the issue
I'm using the Sonata System project.

## My Environment

**EDA tool and version:**
Verilator 5.023 devel rev v5.020-200-g88831ca21

**Operating system:**
Ubuntu 20.04

**Version of the Ibex source code:**
Sonata main with RV32E parameter set at the ibex_top level

**Comment by marnovandermaas** [comment]
Thanks for the patch, definitely useful to fix this lint issues.

**Comment by kliuMsft** [comment]
Please try [a2f2976](https://github.com/microsoft/cheriot-ibex/commit/a2f29763a817327c2b1b2e1a649c50343faf8e5f). Verilator compilation works for me on this commit.

**Comment by ColinSCISemi** [comment]
Hi Kunyan,

It looks like you might have some missing lint checks in Verilator. In particular, I'm seeing a lot of WIDTHEXPAND and WIDTHTRUNC errors in the cheri_trvk_stage module.
![image](https://github.com/user-attachments/assets/e1cb6fda-2e9c-4835-b477-13e6733b1c94)

I've currently got the following Verilator command line (which has a lot less tough lint optioning as compared with the Sonata project)
`verilator -f lowrisc_sonata_system_0.vc -DDISABLE_PRIM_CDC_RAND_DELAY --trace --trace-fst --trace-structs --trace-params --trace-max-array 1024 --notiming -CFLAGS "-Wall -DVM_TRACE_FMT_FST -DTOPLEVEL_NAME=top_verilator" -LDFLAGS "-pthread -lutil -lelf" -Wall -Wno-UNOPTFLAT -Wno-GENUNNAMED -Wno-STMTDLY -Wwarn-IMPERFECTSCH -Wno-ASSIGNDLY -Wno-UNUSEDSIGNAL +define+RVFI --unroll-count 72 -j 4`

Cheers

**Comment by ColinSCISemi** [comment]
Or, maybe, you are not setting RV32E parameter in your compile?

**Comment by kliuMsft** [comment]
I did set RV32E, but my verilator setting probably is different from yours. I can't say I fully agree with verilator's lint rules, in my opinion, some of those (data width, e.g.) hurt code quality rather than improve it. However, the index width complaints probably should be fixed (even though they aren't real RTL issues since the cheriot_ibex design guarantee all regfile addresses <=16 when cheri_pmode=1). I can look into that.

**Comment by kliuMsft** [comment]
Please take at the latest commit [3f0ec86](https://github.com/microsoft/cheriot-ibex/commit/3f0ec8600cb7621c4c952951d211b3515116ea27). Basically,
1. RV32E is now a top-level parameter at ibexc_top_tracing level.
2. In ibexc_top, NCAPS now fixed to 16.
3. I took a closer look at the verilator warnings. Currently, I have -Wno-WIDTH and -Wno-UNOPTFLAT in my setup. Basically I am not convinced that the verilator WIDTH warnings provides much value and OPTFLAT warnings keep declaring false combinatorial loops. So I would recommend keeping those 2 warnings turned off.
