### ISSUE TITLE
Issue with illegal_reg_rv32e when RV32E

### ISSUE THREAD

**Issue by esdatmisarian** [microsoft/cheriot-ibex#40]
Instruction sw x20, -1982(x3) is not seen as illegal with RV32E
Waveform:
![issue_on_illegal_instruction_cheri](https://github.com/user-attachments/assets/5ede1542-188a-44ea-8e19-efa8ceb3a4a9)

  if (RV32E) begin : gen_rv32e_reg_check_active
    assign illegal_reg_rv32e = ((rf_raddr_a_o[4] & (alu_op_a_mux_sel_o == OP_A_REG_A)) |
                                (rf_raddr_b_o[4] & (alu_op_b_mux_sel_o == OP_B_REG_B)) |
                                (rf_waddr_o[4]   & rf_we));
 
version:
https://github.com/microsoft/cheriot-ibex/commit/5e4798f67417bcf87c831c56b8980af0e5d3966c

**Comment by kliuMsft** [comment]
Very good finding, thanks! 

@marnovandermaas, this might be an issue for upstream ibex as well.

**Comment by marnovandermaas** [comment]
I think this is related to: https://github.com/lowRISC/ibex/issues/2178

**Comment by esdatmisarian** [comment]
Yes totally agree.
Rgds

**Comment by kliuMsft** [comment]
New commit [a57ec46](https://github.com/microsoft/cheriot-ibex/commit/a57ec46b76c404392ad191b77f5954a6f05d2674) should fix the issue, please help to verify.

**Comment by esdatmisarian** [comment]
Sorry for latency in feedback, it is well corrected.

  *   Verification is OK
Rgds

**Comment by kliuMsft** [comment]
Thanks for the confirmation. I am closing the issue then.
